### PR TITLE
ACF Compatibility: Renamed jQuery.timepicker to jQuery.wpcmtimepicker.

### PR DESCRIPTION
**Pull request by DaveyJake**
Renaming the plugin ensures complete ACF compatibility with no conflicts at runtime.  The `timepicker` now works as expected.  The changes made for this to work include the following:

- Renamed `$.fn.timepicker` to `$.fn.wpcmtimepicker`.
- Updated the `jquery-timepicker` plugin instances in `meta-boxes` and `jquery.timepicker` files.
- Reverted the `WPCM_Admin_Assets` class file to its original version with no conditional checks.
- Optimized the `meta-boxes.js` module using WordPress linter rules.
- Updated `jquery-timepicker` from version `1.11.13` -> `1.13.0`.

### CODE REVIEW

**Comment by roofdog** [comment]
Hi Davey,

Sorry for the delay into looking into these changes! I moved house earlier this week and have only just got back online!

I'll properly review these commits and get back to you very soon.

Cheers

**Comment by roofdog** [comment]
Hi Davey,

What issue was being caused after the last merge using WP conditionals to check if the script should be loaded dependant on ACF?

I don't really want to be editing and renaming the jquery.timepicker script as that could well cause issues with maintaining the plugin in the future.

Cheers

**Comment by DaveyJake** [comment]
Hey mate!

The ACF plugin using a different [jQuery Timepicker plugin](https://trentrichardson.com/examples/timepicker/) from a completely different codebase.  The issue is a namespace conflict as both use the same `$.fn.timepicker` method.

When ACF and WPCM are used on the same post type (`wpcm_match` in this case), the ACF gets loaded long the WPCM version does.  As a result, the UI when selecting a match date becomes unusable and doesn't function at all as expected.

**Comment by roofdog** [comment]
Hi mate,

Sorry for the delays! Things are a bit crazy over here with the lock down... strange times indeed.

Thanks for the reply. I would then be inclined to revert our timepicker script to the same one used by ACF, which uses jQuery UI so will be a good fit anyway. I would rather maintain the separate field for the match time in the match admin page so we could use the .timepicker object.

Then we should use WP conditional functions to enqueue scripts if ACF isn't installed.

**Comment by roofdog** [comment]
Hey Davey,

I've taken a good look into this now and am going to resort to your suggestion as I much prefer the timepicker plugin we are already using!

I've forked the jquery-timepicker plugin and renamed the function. I've committed the new timepicker version to the dev branch so feel free to check it out and give me feedback before I release v2.1.10.

Thanks for your help again :)

**Pull request closed without merging**
